// <auto-generated />
namespace Gauntlet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Workingonvideoupload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Workingonvideoupload));
        
        string IMigrationMetadata.Id
        {
            get { return "201703292006451_Working on video upload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
