// <auto-generated />
namespace Gauntlet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gotuservideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gotuservideo));
        
        string IMigrationMetadata.Id
        {
            get { return "201704062248515_got user video"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
